<?php

namespace RicardoMartins\PagBank\Api\Connect\PaymentMethod;

/**
 * Interface CardInterface - Payment card object.
 * @see https://dev.pagbank.uol.com.br/reference/objeto-order
 * @see https://dev.pagbank.uol.com.br/reference/criptografia
 * @see https://dev.pagbank.uol.com.br/reference/criar-pagar-pedido-com-cartao
 */
interface CardInterface
{
    /**
     * Credit card number.
     * Receives a string with the card number.
     * Characters limit: 14 to 19 characters.
     */
    public const NUMBER = 'number';

    /**
     * Credit card encrypted number.
     * Generated by the PagSeguro.js library.
     * Path: pagBankSdk
     * @see RicardoMartins_PagBank/js/lib/pagseguro
     */
    public const ENCRYPTED = 'encrypted';

    /**
     * Credit card expiration month.
     * Receives an integer with the card expiration month.
     * Characters limit: 1 or 2 characters.
     */
    public const EXPIRATION_MONTH = 'exp_month';

    /**
     * Credit card expiration year.
     * Receives a integer with the card expiration year.
     * Characters limit: 3 or 4 characters.
     */
    public const EXPIRATION_YEAR = 'exp_year';

    /**
     * Credit card security code.
     * Receives a string with the card security code.
     * Characters limit: 3 or 4 characters.
     */
    public const SECURITY_CODE = 'security_code';

    /**
     * Stores the card in PagBank for future use.
     * Receives a boolean. Default is false.
     */
    public const STORE = 'store';

    /**
     * Card brand.
     * Receives a string with the card brand.
     * Characters limit: 1 to 20 characters.
     */
    public const BRAND = 'brand';

    /**
     * Contains the cardholder data.
     * Receives an array.
     * @see \RicardoMartins\PagBank\Api\Connect\HolderInterface
     */
    public const HOLDER = 'holder';

    /**
     * Card ID.
     * Receives a string with the PagBank Card ID.
     * Characters limit: 41 characters.
     */
    public const CARD_ID = 'id';
}
