<?php
/**
 * @var $block \RicardoMartins\PagBank\Block\ConfigurableInfo
 * @var $escaper \Magento\Framework\Escaper
 */
$specificInfo = $block->getSpecificInformation();
$title = $escaper->escapeHtml($block->getMethod()->getTitle());
?>
<?php if ($specificInfo): ?>
    <table class="data-table admin__table-secondary ricardomartins-pagbank">
        <caption class="table-caption"><?= /* @noEscape */ $title ?></caption>
        <?php foreach ($specificInfo as $label => $value) : ?>
            <?php if (!$value): ?>
                <?php continue; ?>
            <?php endif; ?>
            <tr>
                <?php if (is_array($value)): ?>
                    <?php foreach ($value as $type => $valueInner) : ?>
                        <?php if($type === 'link'): ?>
                            <td colspan="2">
                                <a href="<?= $escaper->escapeHtmlAttr($valueInner) ?>" target="_blank"><?= $escaper->escapeHtml($label) ?></a>
                            </td>
                        <?php elseif($type === 'yesno'): ?>
                            <th scope="row"><?= $escaper->escapeHtml($label) ?></th>
                            <td>
                                <?= $valueInner ? __('Yes') : __('No') ?>
                            </td>
                        <?php elseif($type === 'image'): ?>
                            <th scope="row"><?= $escaper->escapeHtml($label) ?></th>
                            <td>
                                <img src="<?= $escaper->escapeHtmlAttr($valueInner) ?>" alt="<?= $escaper->escapeHtmlAttr($label) ?>" width="200px"/>
                            </td>
                        <?php elseif($type === 'copy'): ?>
                            <th scope="row"><?= $escaper->escapeHtml($label) ?></th>
                            <td>
                                <div class="code-container">
                                    <input type="text" id="payment-code" class="payment-code" value="<?= $valueInner; ?>" readonly="readonly"/>
                                    <img src="<?= $block->getViewFileUrl('RicardoMartins_PagBank::images/copy-icon.svg') ?>" alt="<?= $escaper->escapeHtmlAttr(__('Copy')) ?>" title="<?= $escaper->escapeHtmlAttr(__('Copy')) ?>" class="copy-btn"/>
                                </div>
                                <p class="copied" style="display: none"><?= $escaper->escapeHtml(__('Copied ✔')) ?></p>
                            </td>
                        <?php else: ?>
                            <th scope="row"><?= $escaper->escapeHtml($label) ?></th>
                            <td>
                                <?= /* @noEscape */ nl2br($escaper->escapeHtml(implode("\n", $block->getValueAsArray($value, true)))) ?>
                            </td>
                        <?php endif; ?>
                    <?php endforeach; ?>
                <?php else: ?>
                    <th scope="row"><?= $escaper->escapeHtml($label) ?></th>
                    <td>
                        <?= /* @noEscape */ nl2br($escaper->escapeHtml(implode("\n", $block->getValueAsArray($value, true)))) ?>
                    </td>
                <?php endif; ?>
            </tr>
        <?php endforeach; ?>
    </table>
<?php endif;?>
<?= $block->getChildHtml() ?>
<script type="text/x-magento-init">
{
    ".copy-btn": {
        "RicardoMartins_PagBank/js/action/copy-button": {}
    }
}
</script>
